SELECT
    SUM(CASE WHEN BMI < 18.5 THEN 1 ELSE 0 END) AS [0-18.5],
    SUM(CASE WHEN BMI < 24.5 AND BMI >=18.5 THEN 1 ELSE 0 END) AS [18.5-24.5],
    SUM(CASE WHEN BMI < 29.9 AND BMI >=24.5 THEN 1 ELSE 0 END) AS [24.5-29.9],
    SUM(CASE WHEN BMI > 29.9 THEN 1 ELSE 0 END) AS [>29.9]
	FROM S1
	WHERE HeartDisease='Yes';

	SELECT 
	SUM(CASE WHEN Smoking='Yes' THEN 1 ELSE 0 END) AS [SMOKING PATIENTS]
	FROM S1
	WHERE HeartDisease='Yes';

	SELECT 
	SUM(CASE WHEN AlcoholDrinking='Yes' THEN 1 ELSE 0 END) AS [DRINKING PATIENTS]
	FROM S1
	WHERE HeartDisease='Yes';

	SELECT 
	SUM(CASE WHEN AlcoholDrinking='Yes' AND Smoking='Yes'  THEN 1 ELSE 0 END) AS [SMOKING AND DRINKING PATIENTS]
	FROM S1
	WHERE HeartDisease='Yes';

	SELECT
	SUM(CASE WHEN Stroke='Yes' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [ PATIENT WITH STROKE],
	SUM(CASE WHEN Asthma='Yes' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [ PATIENT WITH ASTHMA],
	SUM(CASE WHEN KidneyDisease='Yes' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [ PATIENT WITH KIDNEY DISEASE],
	SUM(CASE WHEN SkinCancer='Yes' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [ PATIENT WITH SKINCANCER]
    FROM S1;

	SELECT
	SUM(CASE WHEN Stroke='Yes' AND HeartDisease ='Yes' AND Asthma='Yes' AND KidneyDisease='Yes' AND  SkinCancer='Yes' THEN 1 ELSE 0 END) AS [ PATIENT WITH ALL]
	FROM S1;



	SELECT 
	SUM(CASE WHEN Sex='Male' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [MALE SUFFERING FROM HAERT DISEASE],
	SUM(CASE WHEN Sex='Female' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [FEMALE SUFFERING FROM HAERT DISEASE]
	FROM S1;


	SELECT 	

	SUM(CASE WHEN AgeCategory='18-24'THEN 1 ELSE 0 END) AS [AGE BETWEEN 18-24],
	SUM(CASE WHEN AgeCategory='25-29'THEN 1 ELSE 0 END) AS [AGE BETWEEN 25-29],
	SUM(CASE WHEN AgeCategory='30-34'THEN 1 ELSE 0 END) AS [AGE BETWEEN 30-34],
	SUM(CASE WHEN AgeCategory='35-39'THEN 1 ELSE 0 END) AS [AGE BETWEEN 35-39],
	SUM(CASE WHEN AgeCategory='40-44'THEN 1 ELSE 0 END) AS [AGE BETWEEN 40-44],
	SUM(CASE WHEN AgeCategory='45-49'THEN 1 ELSE 0 END) AS [AGE BETWEEN 45-49],
	SUM(CASE WHEN AgeCategory='50-54'THEN 1 ELSE 0 END) AS [AGE BETWEEN 50-54],
	SUM(CASE WHEN AgeCategory='55-59'THEN 1 ELSE 0 END) AS [AGE BETWEEN 55-59],
	SUM(CASE WHEN AgeCategory='60-64'THEN 1 ELSE 0 END) AS [AGE BETWEEN 60-64],
	SUM(CASE WHEN AgeCategory='65-69'THEN 1 ELSE 0 END) AS [AGE BETWEEN 65-69],
	SUM(CASE WHEN AgeCategory='70-74'THEN 1 ELSE 0 END) AS [AGE BETWEEN 70-74],
	SUM(CASE WHEN AgeCategory='75-79'THEN 1 ELSE 0 END) AS [AGE BETWEEN 75-79],
	SUM(CASE WHEN AgeCategory='80 or older'THEN 1 ELSE 0 END) AS [AGE BETWEEN 80 or older]

	FROM S1
	WHERE HeartDisease='Yes';

	SELECT 
	SUM(CASE WHEN PhysicalActivity='Yes'THEN 1 ELSE 0 END) AS [PHYICAL ACTIVITY + HEART DISEASE],
	SUM(CASE WHEN PhysicalActivity='No'THEN 1 ELSE 0 END) AS [NO PHYICAL ACTIVITY + HEART DISEASE]
	FROM S1
	WHERE HeartDisease='Yes';

	SELECT AgeCategory,
	SUM(CASE WHEN BMI < 18.5 THEN 1 ELSE 0 END) AS [0-18.5],
    SUM(CASE WHEN BMI < 24.5 AND BMI >=18.5 THEN 1 ELSE 0 END) AS [18.5-24.5],
    SUM(CASE WHEN BMI < 29.9 AND BMI >=24.5 THEN 1 ELSE 0 END) AS [24.5-29.9],
    SUM(CASE WHEN BMI > 29.9 THEN 1 ELSE 0 END) AS [>29.9],
	SUM(CASE WHEN Smoking='Yes' THEN 1 ELSE 0 END) AS [SMOKING PATIENTS],
	SUM(CASE WHEN AlcoholDrinking='Yes' THEN 1 ELSE 0 END) AS [DRINKING PATIENTS],
	SUM(CASE WHEN AlcoholDrinking='Yes' AND Smoking='Yes'  THEN 1 ELSE 0 END) AS [SMOKING AND DRINKING PATIENTS],
	SUM(CASE WHEN Stroke='Yes' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [ PATIENT WITH STROKE],
	SUM(CASE WHEN Asthma='Yes' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [ PATIENT WITH ASTHMA],
	SUM(CASE WHEN KidneyDisease='Yes' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [ PATIENT WITH KIDNEY DISEASE],
	SUM(CASE WHEN SkinCancer='Yes' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [ PATIENT WITH SKINCANCER],
	SUM(CASE WHEN PhysicalActivity='Yes'THEN 1 ELSE 0 END) AS [PHYICAL ACTIVITY + HEART DISEASE],
	SUM(CASE WHEN PhysicalActivity='No'THEN 1 ELSE 0 END) AS [NO PHYICAL ACTIVITY + HEART DISEASE],
	SUM(CASE WHEN Sex='Male' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [MALE SUFFERING FROM HAERT DISEASE],
	SUM(CASE WHEN Sex='Female' AND HeartDisease ='Yes' THEN 1 ELSE 0 END) AS [FEMALE SUFFERING FROM HAERT DISEASE]

	FROM S1
	WHERE HeartDisease='Yes'
	GROUP BY AgeCategory;


	














	